modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/fallOut015/hud_quiver/issues" #optional
[[mods]] #mandatory
modId="hud_quiver" #mandatory
version="${file.jarVersion}" #mandatory
displayName="HUD Quiver" #mandatory
updateJSONURL="https://raw.githubusercontent.com/fallOut015/hud_quiver/main/src/main/resources/updateJSONURL.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/hud-quiver" #optional
logoFile="hud_quiver.png" #optional
credits="Forge, tutorial makers, and my friends" #optional
authors="fallOut015" #optional
description='''
A bite-sized mod that adds an indicator for your arrows.
'''
[[dependencies.hud_quiver]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.hud_quiver]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
